# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/clients.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.table_clients = QtWidgets.QTableView(Dialog)
        self.table_clients.setGeometry(QtCore.QRect(0, 0, 391, 191))
        self.table_clients.setObjectName("table_clients")
        self.btn_add = QtWidgets.QPushButton(Dialog)
        self.btn_add.setGeometry(QtCore.QRect(0, 200, 93, 28))
        self.btn_add.setObjectName("btn_add")
        self.btn_edit = QtWidgets.QPushButton(Dialog)
        self.btn_edit.setGeometry(QtCore.QRect(0, 230, 111, 28))
        self.btn_edit.setObjectName("btn_edit")
        self.btn_delit = QtWidgets.QPushButton(Dialog)
        self.btn_delit.setGeometry(QtCore.QRect(0, 260, 93, 28))
        self.btn_delit.setObjectName("btn_delit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_add.setText(_translate("Dialog", "Добавить"))
        self.btn_edit.setText(_translate("Dialog", "Редактировать"))
        self.btn_delit.setText(_translate("Dialog", "Удалить"))
